### PR TITLE
Add options for shell command

### PR DESCRIPTION
**Pull request by grimpy**
Make it possible to pass window_name and shell command to
server.new_session
Make it possible to pass shell command to window.split_window

Signed-off-by: Jo De Boeck <deboeck.jo@gmail.com>

### CODE REVIEW

**Comment by grimpy** [comment]
Apprently this implemnts #87

**Comment by tony** [comment]
Is there any chance this can get a test?

**Comment by grimpy** [comment]
Yes was still looking how tests are done in this project will update the PR
when I find some time to work on it.

**Comment by grimpy** [comment]
Tests added

**Comment by tony** [comment]
Sorry for the late response, I am having issues keeping up wit the project. I'm seeking maintainers @ https://github.com/tony/tmuxp/issues/290. If you (or someone you know) may be interested in helping maintain libtmux or tmuxp, feel free to contact me by email or in the https://github.com/tony/tmuxp/issues/290 issue.

**Comment by tony** [comment]
I rebased on your behalf to trigger CI (org move, changes). b0fa5669e4a24615dd47ca8a09477c1fdbfd8a71 -> 654ad41

**Comment by tony** [comment]
When I rebased, the commit shows up differently. The UI no longer shows you signed off on it, though the git commit message is the same. I didn't know that would happen.

screen shot 2018-03-11 at 3 19 25 pm

**Comment by tony** [comment]
I want to do a release today, ideally. I don't have much time during the weekdays.

If this rebase at 654ad41 gets in the way - let me know and I'll force push it out of master and reset things. Though - I'd plan to rebase and merge via GitHub anyway...

Also, if I find that GH doesn't give you credit for the commit - I'm going to revert it to make sure you do.

This is my mistake. I didn't know the PR "add more commits" feature would react that way (i.e. this feature is how I rebased your PR):
screen shot 2018-03-11 at 3 24 05 pm

**Comment by grimpy** [comment]
@tony don't worry about it, I dont mind not getting the credit I rather have it in the release :)
I did rebase myself and push to my branch it seems to have fixed it though

**Comment by tony** [comment]
> I did rebase myself and push to my branch it seems to have fixed it though

That's awesome. :)

**Pull request merged**
