### PR TITLE
Fix deprecation warning when using collection.MutableMapping

### LINKED ISSUE #277: Deprecation warning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
I get the above deprecation warning when importing libtmux

```
  import libtmux
  File "env/lib/python3.8/site-packages/libtmux/__init__.py", line 16, in <module>
    from .pane import Pane
  File "env/lib/python3.8/site-packages/libtmux/pane.py", line 13, in <module>
    from .common import TmuxMappingObject, TmuxRelationalObject
  File "env/lib/python3.8/site-packages/libtmux/common.py", line 221, in <module>
    class TmuxMappingObject(collections.MutableMapping):
  File "/usr/lib/python3.8/collections/__init__.py", line 49, in __getattr__
    warnings.warn("Using or importing the ABCs from 'collections' instead "
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
```

### PR DESCRIPTION
**Pull request by d1618033**
fixes #277

### CODE REVIEW

**Comment by tony** [comment]
@d1618033 Hi there, sorry for the delay, can you rebase?

**Comment by d1618033** [comment]
@tony rebased

**Comment by d1618033** [comment]
@tony do you want me to do anything else?

**Comment by tony** [comment]
@d1618033 Merged!  Thank you

**Pull request merged**
