### PR TITLE
Fix crash on calling Server.attached_sessions

### LINKED ISSUE #180: Possible bug in attached_sessions() method
Calling the `attached_sesssions` method of a `Server` object raises the following exception:
```
In [20]: import libtmux

In [21]: server = libtmux.Server()

In [22]: server.attached_sessions
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-22-aee9c49879f2> in <module>()
----> 1 server.attached_sessions

/dccstor/faceid/code/anaconda3/x86_64/envs/mxnet/lib/python2.7/site-packages/libtmux/server.pyc in attached_sessions(self)
    336             if 'session_attached' in session:
    337                 # for now session_active is a unicode
--> 338                 if session.attached == '1':
    339                     logger.debug('session %s attached', session.name)
    340                     attached_sessions.append(session)

AttributeError: 'dict' object has no attribute 'attached'
```
Seems that `line 338` above expects an object of type `Session` while it is actually a `dict`.
Using `libtmux=0.81` and `python=2.7`

### PR DESCRIPTION
**Pull request by Timoses**
fixes #180

### CODE REVIEW

**Comment by tony** [comment]
@Timoses Can you rebase this and #342 so tests run?  Thank you!

**Comment by Timoses** [comment]
@tony : Done ; )

**Comment by tony** [comment]
@Timoses Thank you!

**Comment by tony** [comment]
Merged via #342 @ 7198957c9e1bf0bdad476f2310c60a19773e83db, 

Thank you @Timoses!

**Pull request closed without merging**
