### PR TITLE
test(test_capture_pane): Remove bashism(s)

### LINKED ISSUE #454: Remove BASH-isms from tests
re: https://github.com/tmux-python/libtmux/pull/452#discussion_r1014638444, https://github.com/tmux-python/tmuxp/pull/844

### PR DESCRIPTION
**Pull request by tony**
Fixes #454

### CODE REVIEW

**Comment by tony** [comment]
@zappolowski How is this for you? (in re: https://github.com/tmux-python/tmuxp/pull/844)

Do any tests fail w/ libtmux?

**Comment by zappolowski** [comment]
It's still the doctest from `src/libtmux/pane.py:159` which fails. That test also seems a bit flaky as the captured value either is empty `[]` or (as mentioned somewhere else) the default prompt of bash which is `PS1=\s-\v$ ` and thus `['sh-5.1$']`.

I still have no clue how this issue could be resolved, but as already stated its easy to ignore for humans - as long as the CI uses `dash` it won't fail.

**Comment by tony** [comment]
I will take care of it - but I don't have an ETA yet (until I understand it better / reproduce it reliably)

**Comment by tony** [comment]
@zappolowski This is an existential issue for libtmux / tmuxp

I think it's going to take some thinking.

Ideas: 

- sending a sentinel command made to figure out what the PS1 and shell is.
- building in support for polling `capture_pane()` (similar to playwright / selenium)
- finding "flake-free" / "rock-solid" loadouts for capturing pane text. Reliable enough to be used downstream in tests and across platforms

What we need:

- We need to know what `capture_pane()` and etc. is being used for.  Can that spare to use a no-frills shell if it gives them rock-solid results across platforms?

**Pull request merged**
